### ISSUE TITLE
Data download issue

### ISSUE THREAD

**Issue by DamianMYM** [CoDS-GCS/KGQAn#4]
Hi, 

I believe the download script for data is invalid, in which  I found that 'https://docs.google.com/uc?export=download&id=149tB7x_dYLfmwoEdCfKfjBNeGdqFvqOP' is 404 when I tried to download it separately.

I'm looking forward to hearing back from you!

Many thanks,
Damian

**Comment by Reham-Osama** [comment]
Hi Damian,

Can you please try with the following link:
https://drive.google.com/file/d/1QbT5FDOJtdVd7AqZ-ekwUh2_pn6nNpb3/view?usp=sharing
https://drive.google.com/file/d/1UTPGv8QUgqSVQ2JeX9QVW0YhbGRxONLL/view?usp=drive_link

It looks like there is a new update in Google Drive that prevents us from downloading the file using wget, so you can download the file separately using these links and then run the script to adjust the project structure requirements.

**Comment by DamianMYM** [comment]
Hi Reham,

Thanks for your kind reply!!

There is one more question I would like to ask which is how much GPU resources do I need to run it?
Currently, I am trying to start kgqan server to run your model and I met some issues. I ran it overnight with two 4090 and somehow it returned a timeout error like socket.timeout: The read operation timed out,  while I put the command python -m kgqan.server.

So I am trying to do it again, but I wanna know is it normal?  I mean, spends so much time to initiate the server, and it also shows './KGQAn/src/kgqan/model  Invalid Seq2Seq model path' IDK if it affects the results. Luckily, the word-embedding functionality is started smoothly.

I'm looking forward to hearing back from you again!

Many thanks,
Damian

**Comment by Reham-Osama** [comment]
Hi Damian,

- You can run without GPU. Using GPU will make it faster. The code is tested with a machine with NVIDIA Tesla P100 and with CPU machines, and it worked correctly in both.
- It shouldn't take that long to run the server, Please show me the issue, so I can help.
- For this error message: **/KGQAn/src/kgqan/model Invalid Seq2Seq model**, The downloaded model was not placed in the correct directory, after you download the model it should be copied to this directory as performed in the data download script. If the model is not loaded correctly, the system will not run as expected. Move to the model to the correct directory and Let me know if there exists any other issue.
