### ISSUE TITLE
kgqan server mode issue

### ISSUE THREAD

**Issue by DamianMYM** [CoDS-GCS/KGQAn#5]
Hi Reham, 

As I ran it again, I found that there was no more response after the following output.
`(kgqan) root@autodl-container-da414883cd-4d3ea7fd:~/autodl-tmp/KGQAn/src# python -m kgqan.server
[nltk_data] Downloading package wordnet to nltk_cache...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to nltk_cache...
[nltk_data]   Package punkt is already up-to-date!
/root/autodl-tmp/KGQAn/src/kgqan/model
Invalid Seq2Seq model path
`

I had been waiting for the terminal's response for a long time, and I didn't know what was going on. I'll try the other one mode later on to see if it works.

Would you please give me some ideas on this? Looking forward to your reply.

Many thanks,
Damian

**Comment by Reham-Osama** [comment]
Hi Damian,

Make sure that the downloaded model is in the correct path. Please should be what exists under the directory: _KGQAn/src/kgqan/model_, so I can help.

**Comment by DamianMYM** [comment]
Hello Reham,

Thanks for your quick reply, and it is very useful!

This time I set up the correct path and started kgqan server again, it could load the model properly.
**BUT,** I had been waiting for like 1h and nothing shown on the terminal after automately downloading everything, which I should have expected this message: Server started http://0.0.0.0:8899
<img width="879" alt="image" src="https://github.com/CoDS-GCS/KGQAn/assets/113518689/f7f7ebf0-aa25-4638-b227-6cd9a6ddfc41">

<img width="884" alt="image" src="https://github.com/CoDS-GCS/KGQAn/assets/113518689/24ff2fbf-ba01-46e7-924f-c09e26c582e3">
I do have another terminal operating the word-embedding server simultaneously like this.
<img width="885" alt="image" src="https://github.com/CoDS-GCS/KGQAn/assets/113518689/59c5517f-e7c7-48e5-b2df-e44204b8fc69">
